---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Balloons
description: Learn how to make a balloon-popping game!
original_url: https://codeclubprojects.org/en-GB/scratch/balloons
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Animating a balloon
- title: Random balloons
- title: 'Challenge: More randomness'
- title: Popping balloons
- title: Adding a score
- title: Lots of balloons
- title: Adding a timer
- title: 'Challenge: More objects'

