---
hero_image: images/banner.png
listed: true
copyedit: true
title: Luftballons
description: Lerne, wie man ein Lass - den - Luftballon - platzen - Spiel erstellt!
version: 4
last_tested: 2018-04-02
steps:
- title: Einleitung
- title: Einen Luftballon animieren
- title: Zuf채llige Luftballons
  completion:
  - engaged
- title: 'Herausforderung: mehr Zuf채lligkeit'
  challenge: true
- title: Luftballons platzen lassen
- title: Einen Punktestand hinzuf체gen
- title: Viele Luftballons
- title: Hinzuf체gen eines Timers
  completion:
  - internal
- title: 'Herausforderung: mehr Objekte'
  challenge: true
- title: Wie geht es weiter?
