---
hero_image: images/banner.png
listed: true
copyedit: true
title: Ballons
description: Apprends à créer un jeu de ballon à éclater !
version: 4
last_tested: 2018-04-02
steps:
- title: Introduction
  completion: engaged
- title: Animation d'un ballon
- title: Ballons aléatoires
- title: 'Défi : plus de hasard'
  challenge: true
- title: Ballons à éclater
- title: Ajouter un score
- title: Beaucoup de ballons
  completion: internal
- title: Ajouter un chronomètre
- title: 'Défi : plus d''objets'
  challenge: true
- title: Et ensuite ?
