---
hero_image: images/banner.png
listed: true
copyedit: true
title: Palloncini
description: Impara a creare un gioco in cui si fanno scoppiare dei palloncini!
version: 4
last_tested: 2018-04-02
steps:
- title: Introduzione
- title: Animare un palloncino
- title: Palloncini imprevedibili
  completion:
  - engaged
- title: 'Sfida: Aggiungi ancora più casualità'
  challenge: true
- title: Palloncini scoppiettanti
- title: Aggiungere un punteggio
- title: Tanti palloncini
- title: Aggiungere un cronometro
  completion:
  - internal
- title: 'Sfida: Altri oggetti'
  challenge: true
- title: E poi?
